services:
  - type: web
    name: nest-auth
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run start:prod
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: nest-auth-db
          property: connectionString
      - key: SENDGRID_API_KEY
        sync: false
databases:
  - name: nest-auth-db
    plan: free
